package com.hitachi.hibernate.entities;

import com.hitachi.objects.ParseElement;
import com.hitachi.util.HibernateDriver;

// Generated Dec 1, 2011 1:11:07 AM by Hibernate Tools 3.4.0.CR1

/**
 * Arraygroup generated by hbm2java
 */
public class Arraygroup extends HibernateDriver implements java.io.Serializable {

	private ArraygroupId id;
	private long allocatedCapacity;
	private int chassis;
	private int clprNumber;
	private int controllerId;
	private float diskSize;
	private long diskSizeInKb;
	private String diskType;
	private int dpPoolId;
	private String emulation;
	private int encrypted;
	private long freeCapacity;
	private long hiHsmCapacity;
	private long imAllocatedCapacity;
	private long imFreeCapacity;
	private long imHiHsmCapacity;
	private long imOnDemandCapacity;
	private long imTotalCapacity;
	private long largestFreeSpace;
	private long mfAllocatedCapacity;
	private long mfHiHsmCapacity;
	private long mfOnDemandCapacity;
	private long mfTotalCapacity;
	private long mfUnallocatedCapacity;
	private long onDemandCapacity;
	private long openAllocatedCapacity;
	private long openFreeCapacity;
	private long openHiHsmCapacity;
	private long openOnDemandCapacity;
	private long openReservedActualCapacity;
	private long openReservedCapacity;
	private long openTotalCapacity;
	private long openUnallocatedActualCapacity;
	private int protectionLevel;
	private String raidType;
	private int slprNumber;
	private int substance;
	private long totalCapacity;
	private long totalFreeSpace;
	private int type;
	private int volumeType;

	public Arraygroup() {
	}

	public Arraygroup(ArraygroupId id, long allocatedCapacity, int chassis,
			int clprNumber, int controllerId, float diskSize, long diskSizeInKb,
			String diskType, int dpPoolId, String emulation, int encrypted,
			long freeCapacity, long hiHsmCapacity, long imAllocatedCapacity,
			long imFreeCapacity, long imHiHsmCapacity, long imOnDemandCapacity,
			long imTotalCapacity, long largestFreeSpace, long mfAllocatedCapacity,
			long mfHiHsmCapacity, long mfOnDemandCapacity, long mfTotalCapacity,
			long mfUnallocatedCapacity, long onDemandCapacity,
			long openAllocatedCapacity, long openFreeCapacity,
			long openHiHsmCapacity, long openOnDemandCapacity,
			long openReservedActualCapacity, long openReservedCapacity,
			long openTotalCapacity, long openUnallocatedActualCapacity,
			int protectionLevel, String raidType, int slprNumber,
			int substance, long totalCapacity, long totalFreeSpace, int type,
			int volumeType) {
		this.id = id;
		this.allocatedCapacity = allocatedCapacity;
		this.chassis = chassis;
		this.clprNumber = clprNumber;
		this.controllerId = controllerId;
		this.diskSize = diskSize;
		this.diskSizeInKb = diskSizeInKb;
		this.diskType = diskType;
		this.dpPoolId = dpPoolId;
		this.emulation = emulation;
		this.encrypted = encrypted;
		this.freeCapacity = freeCapacity;
		this.hiHsmCapacity = hiHsmCapacity;
		this.imAllocatedCapacity = imAllocatedCapacity;
		this.imFreeCapacity = imFreeCapacity;
		this.imHiHsmCapacity = imHiHsmCapacity;
		this.imOnDemandCapacity = imOnDemandCapacity;
		this.imTotalCapacity = imTotalCapacity;
		this.largestFreeSpace = largestFreeSpace;
		this.mfAllocatedCapacity = mfAllocatedCapacity;
		this.mfHiHsmCapacity = mfHiHsmCapacity;
		this.mfOnDemandCapacity = mfOnDemandCapacity;
		this.mfTotalCapacity = mfTotalCapacity;
		this.mfUnallocatedCapacity = mfUnallocatedCapacity;
		this.onDemandCapacity = onDemandCapacity;
		this.openAllocatedCapacity = openAllocatedCapacity;
		this.openFreeCapacity = openFreeCapacity;
		this.openHiHsmCapacity = openHiHsmCapacity;
		this.openOnDemandCapacity = openOnDemandCapacity;
		this.openReservedActualCapacity = openReservedActualCapacity;
		this.openReservedCapacity = openReservedCapacity;
		this.openTotalCapacity = openTotalCapacity;
		this.openUnallocatedActualCapacity = openUnallocatedActualCapacity;
		this.protectionLevel = protectionLevel;
		this.raidType = raidType;
		this.slprNumber = slprNumber;
		this.substance = substance;
		this.totalCapacity = totalCapacity;
		this.totalFreeSpace = totalFreeSpace;
		this.type = type;
		this.volumeType = volumeType;
	}

	public ArraygroupId getId() {
		return this.id;
	}

	public void setId(ArraygroupId id) {
		this.id = id;
	}

	public long getAllocatedCapacity() {
		return this.allocatedCapacity;
	}

	public void setAllocatedCapacity(long allocatedCapacity) {
		this.allocatedCapacity = allocatedCapacity;
	}

	public int getChassis() {
		return this.chassis;
	}

	public void setChassis(int chassis) {
		this.chassis = chassis;
	}

	public int getClprNumber() {
		return this.clprNumber;
	}

	public void setClprNumber(int clprNumber) {
		this.clprNumber = clprNumber;
	}

	public int getControllerId() {
		return this.controllerId;
	}

	public void setControllerId(int controllerId) {
		this.controllerId = controllerId;
	}

	public float getDiskSize() {
		return this.diskSize;
	}

	public void setDiskSize(float diskSize) {
		this.diskSize = diskSize;
	}

	public long getDiskSizeInKb() {
		return this.diskSizeInKb;
	}

	public void setDiskSizeInKb(long diskSizeInKb) {
		this.diskSizeInKb = diskSizeInKb;
	}

	public String getDiskType() {
		return this.diskType;
	}

	public void setDiskType(String diskType) {
		this.diskType = diskType;
	}

	public int getDpPoolId() {
		return this.dpPoolId;
	}

	public void setDpPoolId(int dpPoolId) {
		this.dpPoolId = dpPoolId;
	}

	public String getEmulation() {
		return this.emulation;
	}

	public void setEmulation(String emulation) {
		this.emulation = emulation;
	}

	public int getEncrypted() {
		return this.encrypted;
	}

	public void setEncrypted(int encrypted) {
		this.encrypted = encrypted;
	}

	public long getFreeCapacity() {
		return this.freeCapacity;
	}

	public void setFreeCapacity(long freeCapacity) {
		this.freeCapacity = freeCapacity;
	}

	public long getHiHsmCapacity() {
		return this.hiHsmCapacity;
	}

	public void setHiHsmCapacity(long hiHsmCapacity) {
		this.hiHsmCapacity = hiHsmCapacity;
	}

	public long getImAllocatedCapacity() {
		return this.imAllocatedCapacity;
	}

	public void setImAllocatedCapacity(long imAllocatedCapacity) {
		this.imAllocatedCapacity = imAllocatedCapacity;
	}

	public long getImFreeCapacity() {
		return this.imFreeCapacity;
	}

	public void setImFreeCapacity(long imFreeCapacity) {
		this.imFreeCapacity = imFreeCapacity;
	}

	public long getImHiHsmCapacity() {
		return this.imHiHsmCapacity;
	}

	public void setImHiHsmCapacity(long imHiHsmCapacity) {
		this.imHiHsmCapacity = imHiHsmCapacity;
	}

	public long getImOnDemandCapacity() {
		return this.imOnDemandCapacity;
	}

	public void setImOnDemandCapacity(long imOnDemandCapacity) {
		this.imOnDemandCapacity = imOnDemandCapacity;
	}

	public long getImTotalCapacity() {
		return this.imTotalCapacity;
	}

	public void setImTotalCapacity(long imTotalCapacity) {
		this.imTotalCapacity = imTotalCapacity;
	}

	public long getLargestFreeSpace() {
		return this.largestFreeSpace;
	}

	public void setLargestFreeSpace(long largestFreeSpace) {
		this.largestFreeSpace = largestFreeSpace;
	}

	public long getMfAllocatedCapacity() {
		return this.mfAllocatedCapacity;
	}

	public void setMfAllocatedCapacity(long mfAllocatedCapacity) {
		this.mfAllocatedCapacity = mfAllocatedCapacity;
	}

	public long getMfHiHsmCapacity() {
		return this.mfHiHsmCapacity;
	}

	public void setMfHiHsmCapacity(long mfHiHsmCapacity) {
		this.mfHiHsmCapacity = mfHiHsmCapacity;
	}

	public long getMfOnDemandCapacity() {
		return this.mfOnDemandCapacity;
	}

	public void setMfOnDemandCapacity(long mfOnDemandCapacity) {
		this.mfOnDemandCapacity = mfOnDemandCapacity;
	}

	public long getMfTotalCapacity() {
		return this.mfTotalCapacity;
	}

	public void setMfTotalCapacity(long mfTotalCapacity) {
		this.mfTotalCapacity = mfTotalCapacity;
	}

	public long getMfUnallocatedCapacity() {
		return this.mfUnallocatedCapacity;
	}

	public void setMfUnallocatedCapacity(long mfUnallocatedCapacity) {
		this.mfUnallocatedCapacity = mfUnallocatedCapacity;
	}

	public long getOnDemandCapacity() {
		return this.onDemandCapacity;
	}

	public void setOnDemandCapacity(long onDemandCapacity) {
		this.onDemandCapacity = onDemandCapacity;
	}

	public long getOpenAllocatedCapacity() {
		return this.openAllocatedCapacity;
	}

	public void setOpenAllocatedCapacity(long openAllocatedCapacity) {
		this.openAllocatedCapacity = openAllocatedCapacity;
	}

	public long getOpenFreeCapacity() {
		return this.openFreeCapacity;
	}

	public void setOpenFreeCapacity(long openFreeCapacity) {
		this.openFreeCapacity = openFreeCapacity;
	}

	public long getOpenHiHsmCapacity() {
		return this.openHiHsmCapacity;
	}

	public void setOpenHiHsmCapacity(long openHiHsmCapacity) {
		this.openHiHsmCapacity = openHiHsmCapacity;
	}

	public long getOpenOnDemandCapacity() {
		return this.openOnDemandCapacity;
	}

	public void setOpenOnDemandCapacity(long openOnDemandCapacity) {
		this.openOnDemandCapacity = openOnDemandCapacity;
	}

	public long getOpenReservedActualCapacity() {
		return this.openReservedActualCapacity;
	}

	public void setOpenReservedActualCapacity(long openReservedActualCapacity) {
		this.openReservedActualCapacity = openReservedActualCapacity;
	}

	public long getOpenReservedCapacity() {
		return this.openReservedCapacity;
	}

	public void setOpenReservedCapacity(long openReservedCapacity) {
		this.openReservedCapacity = openReservedCapacity;
	}

	public long getOpenTotalCapacity() {
		return this.openTotalCapacity;
	}

	public void setOpenTotalCapacity(long openTotalCapacity) {
		this.openTotalCapacity = openTotalCapacity;
	}

	public long getOpenUnallocatedActualCapacity() {
		return this.openUnallocatedActualCapacity;
	}

	public void setOpenUnallocatedActualCapacity(
			long openUnallocatedActualCapacity) {
		this.openUnallocatedActualCapacity = openUnallocatedActualCapacity;
	}

	public int getProtectionLevel() {
		return this.protectionLevel;
	}

	public void setProtectionLevel(int protectionLevel) {
		this.protectionLevel = protectionLevel;
	}

	public String getRaidType() {
		return this.raidType;
	}

	public void setRaidType(String raidType) {
		this.raidType = raidType;
	}

	public int getSlprNumber() {
		return this.slprNumber;
	}

	public void setSlprNumber(int slprNumber) {
		this.slprNumber = slprNumber;
	}

	public int getSubstance() {
		return this.substance;
	}

	public void setSubstance(int substance) {
		this.substance = substance;
	}

	public long getTotalCapacity() {
		return this.totalCapacity;
	}

	public void setTotalCapacity(long totalCapacity) {
		this.totalCapacity = totalCapacity;
	}

	public long getTotalFreeSpace() {
		return this.totalFreeSpace;
	}

	public void setTotalFreeSpace(long totalFreeSpace) {
		this.totalFreeSpace = totalFreeSpace;
	}

	public int getType() {
		return this.type;
	}

	public void setType(int type) {
		this.type = type;
	}

	public int getVolumeType() {
		return this.volumeType;
	}

	public void setVolumeType(int volumeType) {
		this.volumeType = volumeType;
	}
	
	public void populate(ParseElement pElem){
	
		ArraygroupId aid = new ArraygroupId();
		aid.setObjectId(pElem.getAttribute().get("objectID"));
		aid.setDisplayName(pElem.getAttribute().get("displayName"));
		aid.setNumber(Integer.parseInt(pElem.getAttribute().get("number")));
		this.setId(aid);
		this.setAllocatedCapacity(Long.parseLong(pElem.getAttribute().get("allocatedCapacity")));
		this.setChassis(Integer.parseInt(pElem.getAttribute().get("chassis")));
		this.setClprNumber(Integer.parseInt(pElem.getAttribute().get("clprNumber")));
		this.setControllerId(Integer.parseInt(pElem.getAttribute().get("controllerID")));
		this.setDiskSize(Float.parseFloat(pElem.getAttribute().get("diskSize")));
		this.setDiskSizeInKb(Long.parseLong(pElem.getAttribute().get("diskSizeInKB")));
		this.setDiskType(pElem.getAttribute().get("diskType"));
		this.setDpPoolId(Integer.parseInt(pElem.getAttribute().get("dpPoolID")));
		this.setEmulation(pElem.getAttribute().get("emulation"));
		this.setEncrypted(Integer.parseInt(pElem.getAttribute().get("encrypted")));
		this.setFreeCapacity(Long.parseLong(pElem.getAttribute().get("freeCapacity")));
		this.setHiHsmCapacity(Long.parseLong(pElem.getAttribute().get("hiHsmCapacity")));
		this.setImAllocatedCapacity(Long.parseLong(pElem.getAttribute().get("imAllocatedCapacity")));
		this.setImFreeCapacity(Long.parseLong(pElem.getAttribute().get("imFreeCapacity")));
		this.setImHiHsmCapacity(Long.parseLong(pElem.getAttribute().get("imHiHsmCapacity")));
		this.setImOnDemandCapacity(Long.parseLong(pElem.getAttribute().get("imOnDemandCapacity")));
		this.setImTotalCapacity(Long.parseLong(pElem.getAttribute().get("imTotalCapacity")));
		this.setLargestFreeSpace(Long.parseLong(pElem.getAttribute().get("largestFreeSpace")));
		this.setMfUnallocatedCapacity(Long.parseLong(pElem.getAttribute().get("mfUnallocatedCapacity")));
		this.setMfHiHsmCapacity(Long.parseLong(pElem.getAttribute().get("mfHiHsmCapacity")));
		this.setMfOnDemandCapacity(Long.parseLong(pElem.getAttribute().get("mfOnDemandCapacity")));
		this.setMfTotalCapacity(Long.parseLong(pElem.getAttribute().get("mfTotalCapacity")));
		this.setMfUnallocatedCapacity(Long.parseLong(pElem.getAttribute().get("mfUnallocatedCapacity")));
		this.setOnDemandCapacity(Long.parseLong(pElem.getAttribute().get("imOnDemandCapacity")));
		this.setOpenAllocatedCapacity(Long.parseLong(pElem.getAttribute().get("openAllocatedCapacity")));
		this.setOpenFreeCapacity(Long.parseLong(pElem.getAttribute().get("openFreeCapacity")));
		this.setOpenHiHsmCapacity(Long.parseLong(pElem.getAttribute().get("openHiHsmCapacity")));
		this.setOpenOnDemandCapacity(Long.parseLong(pElem.getAttribute().get("openOnDemandCapacity")));
		this.setOpenReservedActualCapacity(Long.parseLong(pElem.getAttribute().get("openReservedActualCapacity")));
		this.setOpenReservedCapacity(Long.parseLong(pElem.getAttribute().get("openReservedCapacity")));
		this.setOpenTotalCapacity(Long.parseLong(pElem.getAttribute().get("openTotalCapacity")));
		this.setOpenUnallocatedActualCapacity(Long.parseLong(pElem.getAttribute().get("openUnallocatedActualCapacity")));
		this.setProtectionLevel(Integer.parseInt(pElem.getAttribute().get("protectionLevel")));
		this.setRaidType(pElem.getAttribute().get("raidType"));
		this.setSlprNumber(Integer.parseInt(pElem.getAttribute().get("slprNumber")));
		this.setSubstance(Integer.parseInt(pElem.getAttribute().get("substance")));
		this.setTotalCapacity(Long.parseLong(pElem.getAttribute().get("imTotalCapacity")));
		this.setTotalFreeSpace(Long.parseLong(pElem.getAttribute().get("totalFreeSpace")));
		this.setType(Integer.parseInt(pElem.getAttribute().get("type")));
		this.setVolumeType(Integer.parseInt(pElem.getAttribute().get("volumeType")));
	}

}
