package com.hitachi.hibernate.entities;

// Generated Dec 1, 2011 1:11:07 AM by Hibernate Tools 3.4.0.CR1

/**
 * ArraygroupId generated by hbm2java
 */
public class ArraygroupId implements java.io.Serializable {

	private int number;
	private String displayName;
	private String objectId;

	public ArraygroupId() {
	}

	public ArraygroupId(int number, String displayName, String objectId) {
		this.number = number;
		this.displayName = displayName;
		this.objectId = objectId;
	}

	public int getNumber() {
		return this.number;
	}

	public void setNumber(int number) {
		this.number = number;
	}

	public String getDisplayName() {
		return this.displayName;
	}

	public void setDisplayName(String displayName) {
		this.displayName = displayName;
	}

	public String getObjectId() {
		return this.objectId;
	}

	public void setObjectId(String objectId) {
		this.objectId = objectId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ArraygroupId))
			return false;
		ArraygroupId castOther = (ArraygroupId) other;

		return (this.getNumber() == castOther.getNumber())
				&& ((this.getDisplayName() == castOther.getDisplayName()) || (this
						.getDisplayName() != null
						&& castOther.getDisplayName() != null && this
						.getDisplayName().equals(castOther.getDisplayName())))
				&& ((this.getObjectId() == castOther.getObjectId()) || (this
						.getObjectId() != null
						&& castOther.getObjectId() != null && this
						.getObjectId().equals(castOther.getObjectId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getNumber();
		result = 37
				* result
				+ (getDisplayName() == null ? 0 : this.getDisplayName()
						.hashCode());
		result = 37 * result
				+ (getObjectId() == null ? 0 : this.getObjectId().hashCode());
		return result;
	}

}
