package com.hitachi.hibernate.entities;

import com.hitachi.objects.ParseElement;
import com.hitachi.util.HibernateDriver;

// Generated Dec 1, 2011 1:12:09 AM by Hibernate Tools 3.4.0.CR1

/**
 * Component generated by hbm2java
 */
public class Component implements java.io.Serializable {

	private ComponentId id;

	public Component() {
	}

	public Component(ComponentId id) {
		this.id = id;
	}

	public ComponentId getId() {
		return this.id;
	}

	public void setId(ComponentId id) {
		this.id = id;
	}
	
	public void populate(ParseElement pElem) {
		
		ComponentId cid = new ComponentId();
		cid.setValue(Integer.parseInt(pElem.getAttribute().get("value")));
		cid.setName(pElem.getAttribute().get("name"));
		cid.setDescription(pElem.getAttribute().get("description"));
		this.setId(cid);
		
		System.out.println(this);
		
	}
}
