package com.hitachi.hibernate.entities;

// Generated Dec 1, 2011 1:12:56 AM by Hibernate Tools 3.4.0.CR1

/**
 * ExternalstorageId generated by hbm2java
 */
public class ExternalstorageId implements java.io.Serializable {

	private long externalCapacityinKb;
	private int numOfExternalVolume;

	public ExternalstorageId() {
	}

	public ExternalstorageId(long externalCapacityinKb, int numOfExternalValue) {
		this.externalCapacityinKb = externalCapacityinKb;
		this.numOfExternalVolume = numOfExternalValue;
	}

	public long getExternalCapacityinKb() {
		return this.externalCapacityinKb;
	}

	public void setExternalCapacityinKb(long externalCapacityinKb) {
		this.externalCapacityinKb = externalCapacityinKb;
	}

	public int getNumOfExternalVolume() {
		return this.numOfExternalVolume;
	}

	public void setNumOfExternalVolume(int numOfExternalVolume) {
		this.numOfExternalVolume = numOfExternalVolume;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ExternalstorageId))
			return false;
		ExternalstorageId castOther = (ExternalstorageId) other;

		return (this.getExternalCapacityinKb() == castOther
				.getExternalCapacityinKb())
				&& (this.getNumOfExternalVolume() == castOther
						.getNumOfExternalVolume());
	}

	public int hashCode() {
		int result = 17;

		result = (int) (37 * result + this.getExternalCapacityinKb());
		result = 37 * result + this.getNumOfExternalVolume();
		return result;
	}

}
