package com.hitachi.hibernate.entities;

import com.hitachi.objects.ParseElement;

// Generated Dec 1, 2011 1:12:56 AM by Hibernate Tools 3.4.0.CR1

/**
 * Externalstorage generated by hbm2java
 */
public class Externalstorage implements java.io.Serializable {

	private ExternalstorageId id;

	public Externalstorage() {
	}

	public Externalstorage(ExternalstorageId id) {
		this.id = id;
	}

	public ExternalstorageId getId() {
		return this.id;
	}

	public void setId(ExternalstorageId id) {
		this.id = id;
	}
	
	public void populate(ParseElement pElem){
		
		ExternalstorageId eid = new ExternalstorageId();
		eid.setExternalCapacityinKb(Long.parseLong(pElem.getAttribute().get("externalCapacityInKB")));
		eid.setNumOfExternalVolume(Integer.parseInt(pElem.getAttribute().get("numOfExternalVolume")));
		this.setId(eid);
	}
}
