package com.hitachi.hibernate.entities;

import com.hitachi.objects.ParseElement;

// Generated Dec 1, 2011 1:13:15 AM by Hibernate Tools 3.4.0.CR1

/**
 * Hoststoragedomain generated by hbm2java
 */
public class Hoststoragedomain implements java.io.Serializable {

	private HoststoragedomainId id;
	private String displayName;
	private int domainType;
	private String hostMode;
	private String hostModeOption;
	private String nickname;
	private String portName;

	public Hoststoragedomain() {
	}

	public Hoststoragedomain(HoststoragedomainId id, String displayName,
			int domainType, String hostMode, String hostModeOption,
			String nickname, String portName) {
		this.id = id;
		this.displayName = displayName;
		this.domainType = domainType;
		this.hostMode = hostMode;
		this.hostModeOption = hostModeOption;
		this.nickname = nickname;
		this.portName = portName;
	}

	public HoststoragedomainId getId() {
		return this.id;
	}

	public void setId(HoststoragedomainId id) {
		this.id = id;
	}

	public String getDisplayName() {
		return this.displayName;
	}

	public void setDisplayName(String displayName) {
		this.displayName = displayName;
	}

	public int getDomainType() {
		return this.domainType;
	}

	public void setDomainType(int domainType) {
		this.domainType = domainType;
	}

	public String getHostMode() {
		return this.hostMode;
	}

	public void setHostMode(String hostMode) {
		this.hostMode = hostMode;
	}

	public String getHostModeOption() {
		return this.hostModeOption;
	}

	public void setHostModeOption(String hostModeOption) {
		this.hostModeOption = hostModeOption;
	}

	public String getNickname() {
		return this.nickname;
	}

	public void setNickname(String nickname) {
		this.nickname = nickname;
	}

	public String getPortName() {
		return this.portName;
	}

	public void setPortName(String portName) {
		this.portName = portName;
	}
	
	public void populate(ParseElement pElem){
		
		HoststoragedomainId hid = new HoststoragedomainId();
		hid.setObjectId(pElem.getAttribute().get("objectID"));
		hid.setDomainId(Integer.parseInt(pElem.getAttribute().get("domainID")));
		hid.setPortId(Integer.parseInt(pElem.getAttribute().get("portID")));
		this.setId(hid);
		this.setDisplayName(pElem.getAttribute().get("displayName"));
		this.setDomainType(Integer.parseInt(pElem.getAttribute().get("domainType")));
		this.setHostMode(pElem.getAttribute().get("hostMode"));
		this.setHostModeOption(pElem.getAttribute().get("hostModeOption"));
		this.setNickname(pElem.getAttribute().get("nickname"));
		this.setPortName(pElem.getAttribute().get("portName"));
	}
}
