package com.hitachi.hibernate.entities;

// Generated Dec 1, 2011 1:13:15 AM by Hibernate Tools 3.4.0.CR1

/**
 * HoststoragedomainId generated by hbm2java
 */
public class HoststoragedomainId implements java.io.Serializable {

	private String objectId;
	private int domainId;
	private int portId;

	public HoststoragedomainId() {
	}

	public HoststoragedomainId(String objectId, int domainId, int portId) {
		this.objectId = objectId;
		this.domainId = domainId;
		this.portId = portId;
	}

	public String getObjectId() {
		return this.objectId;
	}

	public void setObjectId(String objectId) {
		this.objectId = objectId;
	}

	public int getDomainId() {
		return this.domainId;
	}

	public void setDomainId(int domainId) {
		this.domainId = domainId;
	}

	public int getPortId() {
		return this.portId;
	}

	public void setPortId(int portId) {
		this.portId = portId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof HoststoragedomainId))
			return false;
		HoststoragedomainId castOther = (HoststoragedomainId) other;

		return ((this.getObjectId() == castOther.getObjectId()) || (this
				.getObjectId() != null && castOther.getObjectId() != null && this
				.getObjectId().equals(castOther.getObjectId())))
				&& (this.getDomainId() == castOther.getDomainId())
				&& (this.getPortId() == castOther.getPortId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getObjectId() == null ? 0 : this.getObjectId().hashCode());
		result = 37 * result + this.getDomainId();
		result = 37 * result + this.getPortId();
		return result;
	}

}
