package com.hitachi.hibernate.entities;

import com.hitachi.objects.ParseElement;

// Generated Dec 16, 2011 4:51:07 AM by Hibernate Tools 3.4.0.CR1

/**
 * Ldev generated by hbm2java
 */
public class Ldev implements java.io.Serializable {

	private LdevId id;
	private int arrayGroup;
	private String arrayGroupName;
	private int cacheResidencyMode;
	private int chassis;
	private int clprNumber;
	private int consumedSizeInKb;
	private int cylinders;
	private int devType;
	private int diskType;
	private int dpPoolId;
	private int dpTier0consumedCapacityInKb;
	private int dpTier1consumedCapacityInKb;
	private int dpTier2consumedCapacityInKb;
	private String dpType;
	private String emulation;
	private int encrypted;
	private String guardMode;
	private int isComposite;
	private boolean isStandardLdev;
	private int lba;
	private String mfShadowImageVolumeType;
	private String mfTrueCopyVolumeType;
	private int mfUniversalReplicatorPoolId;
	private String mfUniversalReplicatorVolumeType;
	private boolean onDemandDevice;
	private boolean path;
	private String raidType;
	private int sizeInKb;
	private int slotSizeInKb;
	private int slprNumber;
	private String status;
	private int stripeSizeinKb;
	private int substance;
	private int systemDisk;
	private int threshold;
	private int volumeKind;
	private int volumeType;
	private String targetId;
	private String label;

	public Ldev() {
	}

	public Ldev(LdevId id, int arrayGroup, String arrayGroupName,
			int cacheResidencyMode, int chassis, int clprNumber,
			int consumedSizeInKb, int cylinders, int devType, int diskType,
			int dpPoolId, int dpTier0consumedCapacityInKb,
			int dpTier1consumedCapacityInKb, int dpTier2consumedCapacityInKb,
			String dpType, String emulation, int encrypted, String guardMode,
			int isComposite, boolean isStandardLdev, int lba,
			String mfShadowImageVolumeType, String mfTrueCopyVolumeType,
			int mfUniversalReplicatorPoolId,
			String mfUniversalReplicatorVolumeType, boolean onDemandDevice,
			boolean path, String raidType, int sizeInKb, int slotSizeInKb,
			int slprNumber, String status, int stripeSizeinKb, int substance,
			int systemDisk, int threshold, int volumeKind, int volumeType,
			String targetId, String label) {
		this.id = id;
		this.arrayGroup = arrayGroup;
		this.arrayGroupName = arrayGroupName;
		this.cacheResidencyMode = cacheResidencyMode;
		this.chassis = chassis;
		this.clprNumber = clprNumber;
		this.consumedSizeInKb = consumedSizeInKb;
		this.cylinders = cylinders;
		this.devType = devType;
		this.diskType = diskType;
		this.dpPoolId = dpPoolId;
		this.dpTier0consumedCapacityInKb = dpTier0consumedCapacityInKb;
		this.dpTier1consumedCapacityInKb = dpTier1consumedCapacityInKb;
		this.dpTier2consumedCapacityInKb = dpTier2consumedCapacityInKb;
		this.dpType = dpType;
		this.emulation = emulation;
		this.encrypted = encrypted;
		this.guardMode = guardMode;
		this.isComposite = isComposite;
		this.isStandardLdev = isStandardLdev;
		this.lba = lba;
		this.mfShadowImageVolumeType = mfShadowImageVolumeType;
		this.mfTrueCopyVolumeType = mfTrueCopyVolumeType;
		this.mfUniversalReplicatorPoolId = mfUniversalReplicatorPoolId;
		this.mfUniversalReplicatorVolumeType = mfUniversalReplicatorVolumeType;
		this.onDemandDevice = onDemandDevice;
		this.path = path;
		this.raidType = raidType;
		this.sizeInKb = sizeInKb;
		this.slotSizeInKb = slotSizeInKb;
		this.slprNumber = slprNumber;
		this.status = status;
		this.stripeSizeinKb = stripeSizeinKb;
		this.substance = substance;
		this.systemDisk = systemDisk;
		this.threshold = threshold;
		this.volumeKind = volumeKind;
		this.volumeType = volumeType;
		this.targetId = targetId;
		this.label = label;
	}

	public LdevId getId() {
		return this.id;
	}

	public void setId(LdevId id) {
		this.id = id;
	}

	public int getArrayGroup() {
		return this.arrayGroup;
	}

	public void setArrayGroup(int arrayGroup) {
		this.arrayGroup = arrayGroup;
	}

	public String getArrayGroupName() {
		return this.arrayGroupName;
	}

	public void setArrayGroupName(String arrayGroupName) {
		this.arrayGroupName = arrayGroupName;
	}

	public int getCacheResidencyMode() {
		return this.cacheResidencyMode;
	}

	public void setCacheResidencyMode(int cacheResidencyMode) {
		this.cacheResidencyMode = cacheResidencyMode;
	}

	public int getChassis() {
		return this.chassis;
	}

	public void setChassis(int chassis) {
		this.chassis = chassis;
	}

	public int getClprNumber() {
		return this.clprNumber;
	}

	public void setClprNumber(int clprNumber) {
		this.clprNumber = clprNumber;
	}

	public int getConsumedSizeInKb() {
		return this.consumedSizeInKb;
	}

	public void setConsumedSizeInKb(int consumedSizeInKb) {
		this.consumedSizeInKb = consumedSizeInKb;
	}

	public int getCylinders() {
		return this.cylinders;
	}

	public void setCylinders(int cylinders) {
		this.cylinders = cylinders;
	}

	public int getDevType() {
		return this.devType;
	}

	public void setDevType(int devType) {
		this.devType = devType;
	}

	public int getDiskType() {
		return this.diskType;
	}

	public void setDiskType(int diskType) {
		this.diskType = diskType;
	}

	public int getDpPoolId() {
		return this.dpPoolId;
	}

	public void setDpPoolId(int dpPoolId) {
		this.dpPoolId = dpPoolId;
	}

	public int getDpTier0consumedCapacityInKb() {
		return this.dpTier0consumedCapacityInKb;
	}

	public void setDpTier0consumedCapacityInKb(int dpTier0consumedCapacityInKb) {
		this.dpTier0consumedCapacityInKb = dpTier0consumedCapacityInKb;
	}

	public int getDpTier1consumedCapacityInKb() {
		return this.dpTier1consumedCapacityInKb;
	}

	public void setDpTier1consumedCapacityInKb(int dpTier1consumedCapacityInKb) {
		this.dpTier1consumedCapacityInKb = dpTier1consumedCapacityInKb;
	}

	public int getDpTier2consumedCapacityInKb() {
		return this.dpTier2consumedCapacityInKb;
	}

	public void setDpTier2consumedCapacityInKb(int dpTier2consumedCapacityInKb) {
		this.dpTier2consumedCapacityInKb = dpTier2consumedCapacityInKb;
	}

	public String getDpType() {
		return this.dpType;
	}

	public void setDpType(String dpType) {
		this.dpType = dpType;
	}

	public String getEmulation() {
		return this.emulation;
	}

	public void setEmulation(String emulation) {
		this.emulation = emulation;
	}

	public int getEncrypted() {
		return this.encrypted;
	}

	public void setEncrypted(int encrypted) {
		this.encrypted = encrypted;
	}

	public String getGuardMode() {
		return this.guardMode;
	}

	public void setGuardMode(String guardMode) {
		this.guardMode = guardMode;
	}

	public int getIsComposite() {
		return this.isComposite;
	}

	public void setIsComposite(int isComposite) {
		this.isComposite = isComposite;
	}

	public boolean isIsStandardLdev() {
		return this.isStandardLdev;
	}

	public void setIsStandardLdev(boolean isStandardLdev) {
		this.isStandardLdev = isStandardLdev;
	}

	public int getLba() {
		return this.lba;
	}

	public void setLba(int lba) {
		this.lba = lba;
	}

	public String getMfShadowImageVolumeType() {
		return this.mfShadowImageVolumeType;
	}

	public void setMfShadowImageVolumeType(String mfShadowImageVolumeType) {
		this.mfShadowImageVolumeType = mfShadowImageVolumeType;
	}

	public String getMfTrueCopyVolumeType() {
		return this.mfTrueCopyVolumeType;
	}

	public void setMfTrueCopyVolumeType(String mfTrueCopyVolumeType) {
		this.mfTrueCopyVolumeType = mfTrueCopyVolumeType;
	}

	public int getMfUniversalReplicatorPoolId() {
		return this.mfUniversalReplicatorPoolId;
	}

	public void setMfUniversalReplicatorPoolId(int mfUniversalReplicatorPoolId) {
		this.mfUniversalReplicatorPoolId = mfUniversalReplicatorPoolId;
	}

	public String getMfUniversalReplicatorVolumeType() {
		return this.mfUniversalReplicatorVolumeType;
	}

	public void setMfUniversalReplicatorVolumeType(
			String mfUniversalReplicatorVolumeType) {
		this.mfUniversalReplicatorVolumeType = mfUniversalReplicatorVolumeType;
	}

	public boolean isOnDemandDevice() {
		return this.onDemandDevice;
	}

	public void setOnDemandDevice(boolean onDemandDevice) {
		this.onDemandDevice = onDemandDevice;
	}

	public boolean isPath() {
		return this.path;
	}

	public void setPath(boolean path) {
		this.path = path;
	}

	public String getRaidType() {
		return this.raidType;
	}

	public void setRaidType(String raidType) {
		this.raidType = raidType;
	}

	public int getSizeInKb() {
		return this.sizeInKb;
	}

	public void setSizeInKb(int sizeInKb) {
		this.sizeInKb = sizeInKb;
	}

	public int getSlotSizeInKb() {
		return this.slotSizeInKb;
	}

	public void setSlotSizeInKb(int slotSizeInKb) {
		this.slotSizeInKb = slotSizeInKb;
	}

	public int getSlprNumber() {
		return this.slprNumber;
	}

	public void setSlprNumber(int slprNumber) {
		this.slprNumber = slprNumber;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public int getStripeSizeinKb() {
		return this.stripeSizeinKb;
	}

	public void setStripeSizeinKb(int stripeSizeinKb) {
		this.stripeSizeinKb = stripeSizeinKb;
	}

	public int getSubstance() {
		return this.substance;
	}

	public void setSubstance(int substance) {
		this.substance = substance;
	}

	public int getSystemDisk() {
		return this.systemDisk;
	}

	public void setSystemDisk(int systemDisk) {
		this.systemDisk = systemDisk;
	}

	public int getThreshold() {
		return this.threshold;
	}

	public void setThreshold(int threshold) {
		this.threshold = threshold;
	}

	public int getVolumeKind() {
		return this.volumeKind;
	}

	public void setVolumeKind(int volumeKind) {
		this.volumeKind = volumeKind;
	}

	public int getVolumeType() {
		return this.volumeType;
	}

	public void setVolumeType(int volumeType) {
		this.volumeType = volumeType;
	}

	public String getTargetId() {
		return this.targetId;
	}

	public void setTargetId(String targetId) {
		this.targetId = targetId;
	}

	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}
	public void populate(ParseElement pElem){
		
		LdevId lid = new LdevId();
		lid.setObjectId(pElem.getAttribute().get("objectID"));
		lid.setDisplayName(pElem.getAttribute().get("displayName"));
		lid.setDevNum(Integer.parseInt(pElem.getAttribute().get("devNum")));
		this.setId(lid);
		this.setArrayGroup(Integer.parseInt(pElem.getAttribute().get("arrayGroup")));
		this.setArrayGroupName(pElem.getAttribute().get("arrayGroupName"));
		this.setCacheResidencyMode(Integer.parseInt(pElem.getAttribute().get("cacheResidencyMode")));
		this.setChassis(Integer.parseInt(pElem.getAttribute().get("chassis")));
		this.setClprNumber(Integer.parseInt(pElem.getAttribute().get("clprNumber")));
		this.setConsumedSizeInKb(Integer.parseInt(pElem.getAttribute().get("consumedSizeInKB")));
		this.setCylinders(Integer.parseInt(pElem.getAttribute().get("cylinders")));
		if(pElem.getAttribute().get("devType") == "")
			this.setDevType(0);
		else
			this.setDevType(Integer.parseInt(pElem.getAttribute().get("devType")));
		this.setDiskType(Integer.parseInt(pElem.getAttribute().get("diskType")));
		this.setDpPoolId(Integer.parseInt(pElem.getAttribute().get("dpPoolID")));
		this.setDpTier0consumedCapacityInKb(Integer.parseInt(pElem.getAttribute().get("dpTier0ConsumedCapacityInKB")));
		this.setDpTier1consumedCapacityInKb(Integer.parseInt(pElem.getAttribute().get("dpTier1ConsumedCapacityInKB")));
		this.setDpTier2consumedCapacityInKb(Integer.parseInt(pElem.getAttribute().get("dpTier2ConsumedCapacityInKB")));
		this.setDpType(pElem.getAttribute().get("dpType"));
		this.setEmulation(pElem.getAttribute().get("emulation"));
		this.setEncrypted(Integer.parseInt(pElem.getAttribute().get("encrypted")));
		this.setGuardMode(pElem.getAttribute().get("guardMode"));
		this.setIsComposite(Integer.parseInt(pElem.getAttribute().get("isComposite")));
		this.setIsStandardLdev(Boolean.parseBoolean(pElem.getAttribute().get("isStandardLdev")));
		this.setLabel(pElem.getAttribute().get("label"));
		this.setLba(Integer.parseInt(pElem.getAttribute().get("lba")));
		this.setMfShadowImageVolumeType(pElem.getAttribute().get("mfShadowImageVolumeType"));
		this.setMfTrueCopyVolumeType(pElem.getAttribute().get("mfTrueCopyVolumeType"));
		this.setMfUniversalReplicatorPoolId(Integer.parseInt(pElem.getAttribute().get("mfUniversalReplicatorPoolID")));
		this.setMfUniversalReplicatorVolumeType(pElem.getAttribute().get("mfUniversalReplicatorVolumeType"));
		this.setOnDemandDevice(Boolean.parseBoolean(pElem.getAttribute().get("onDemandDevice")));
		this.setPath(Boolean.parseBoolean(pElem.getAttribute().get("path")));
		this.setRaidType(pElem.getAttribute().get("raidType"));
		this.setSizeInKb(Integer.parseInt(pElem.getAttribute().get("consumedSizeInKB")));
		this.setSlprNumber(Integer.parseInt(pElem.getAttribute().get("slprNumber")));
		this.setStatus(pElem.getAttribute().get("status"));
		this.setStripeSizeinKb(Integer.parseInt(pElem.getAttribute().get("stripeSizeInKB")));
		this.setSubstance(Integer.parseInt(pElem.getAttribute().get("substance")));
		this.setSystemDisk(Integer.parseInt(pElem.getAttribute().get("systemDisk")));
		this.setThreshold(Integer.parseInt(pElem.getAttribute().get("threshold")));
		this.setTargetId(pElem.getAttribute().get("targetID"));
		this.setVolumeKind(Integer.parseInt(pElem.getAttribute().get("volumeKind")));
		this.setVolumeType(Integer.parseInt(pElem.getAttribute().get("volumeType")));
	}

}
