package com.hitachi.hibernate.entities;

// Generated Dec 19, 2011 3:53:24 AM by Hibernate Tools 3.4.0.CR1

/**
 * ObjectlabelId generated by hbm2java
 */
public class ObjectlabelId implements java.io.Serializable {

	private String label;
	private String targetId;

	public ObjectlabelId() {
	}

	public ObjectlabelId(String label, String targetId) {
		this.label = label;
		this.targetId = targetId;
	}

	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	public String getTargetId() {
		return this.targetId;
	}

	public void setTargetId(String targetId) {
		this.targetId = targetId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ObjectlabelId))
			return false;
		ObjectlabelId castOther = (ObjectlabelId) other;

		return ((this.getLabel() == castOther.getLabel()) || (this.getLabel() != null
				&& castOther.getLabel() != null && this.getLabel().equals(
				castOther.getLabel())))
				&& ((this.getTargetId() == castOther.getTargetId()) || (this
						.getTargetId() != null
						&& castOther.getTargetId() != null && this
						.getTargetId().equals(castOther.getTargetId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getLabel() == null ? 0 : this.getLabel().hashCode());
		result = 37 * result
				+ (getTargetId() == null ? 0 : this.getTargetId().hashCode());
		return result;
	}

}
