package com.hitachi.hibernate.entities;

import com.hitachi.objects.ParseElement;

// Generated Dec 19, 2011 3:53:24 AM by Hibernate Tools 3.4.0.CR1

/**
 * Objectlabel generated by hbm2java
 */
public class Objectlabel implements java.io.Serializable {

	private ObjectlabelId id;

	public Objectlabel() {
	}

	public Objectlabel(ObjectlabelId id) {
		this.id = id;
	}

	public ObjectlabelId getId() {
		return this.id;
	}

	public void setId(ObjectlabelId id) {
		this.id = id;
	}
	
	public void populate(ParseElement pElem){
		
		ObjectlabelId oid = new ObjectlabelId();
		oid.setLabel(pElem.getAttribute().get("label"));
		oid.setTargetId(pElem.getAttribute().get("targetId"));
		this.setId(oid);
		
	}
}
