package com.hitachi.hibernate.entities;

import com.hitachi.objects.ParseElement;

// Generated Dec 16, 2011 4:25:03 AM by Hibernate Tools 3.4.0.CR1

/**
 * Path generated by hbm2java
 */
public class Path implements java.io.Serializable {

	private String objectId;
	private int lun;
	private int devNum;
	private String displayDevNum;
	private int domainId;
	private int portId;
	private String portName;
	private int scsiId;
	private boolean wwnSecurityValidity;

	public Path() {
	}

	public Path(String objectId, int lun, int devNum, String displayDevNum,
			int domainId, int portId, String portName, int scsiId,
			boolean wwnSecurityValidity) {
		this.objectId = objectId;
		this.lun = lun;
		this.devNum = devNum;
		this.displayDevNum = displayDevNum;
		this.domainId = domainId;
		this.portId = portId;
		this.portName = portName;
		this.scsiId = scsiId;
		this.wwnSecurityValidity = wwnSecurityValidity;
	}

	public String getObjectId() {
		return this.objectId;
	}

	public void setObjectId(String objectId) {
		this.objectId = objectId;
	}

	public int getLun() {
		return this.lun;
	}

	public void setLun(int lun) {
		this.lun = lun;
	}

	public int getDevNum() {
		return this.devNum;
	}

	public void setDevNum(int devNum) {
		this.devNum = devNum;
	}

	public String getDisplayDevNum() {
		return this.displayDevNum;
	}

	public void setDisplayDevNum(String displayDevNum) {
		this.displayDevNum = displayDevNum;
	}

	public int getDomainId() {
		return this.domainId;
	}

	public void setDomainId(int domainId) {
		this.domainId = domainId;
	}

	public int getPortId() {
		return this.portId;
	}

	public void setPortId(int portId) {
		this.portId = portId;
	}

	public String getPortName() {
		return this.portName;
	}

	public void setPortName(String portName) {
		this.portName = portName;
	}

	public int getScsiId() {
		return this.scsiId;
	}

	public void setScsiId(int scsiId) {
		this.scsiId = scsiId;
	}

	public boolean isWwnSecurityValidity() {
		return this.wwnSecurityValidity;
	}

	public void setWwnSecurityValidity(boolean wwnSecurityValidity) {
		this.wwnSecurityValidity = wwnSecurityValidity;
	}
	public void populate(ParseElement pElem){
		
		this.setDevNum(Integer.parseInt(pElem.getAttribute().get("devNum")));
		this.setDisplayDevNum(pElem.getAttribute().get("displayDevNum"));
		this.setDomainId(Integer.parseInt(pElem.getAttribute().get("domainID")));
		this.setLun(Integer.parseInt(pElem.getAttribute().get("LUN")));
		this.setObjectId(pElem.getAttribute().get("objectID"));
		this.setPortId(Integer.parseInt(pElem.getAttribute().get("portID")));
		this.setPortName(pElem.getAttribute().get("portName"));
		this.setScsiId(Integer.parseInt(pElem.getAttribute().get("scsiID")));
		this.setWwnSecurityValidity(Boolean.parseBoolean(pElem.getAttribute().get("wwnSecurityValidity")));
	}
}
