package com.hitachi.hibernate.entities;

import com.hitachi.objects.ParseElement;

// Generated Dec 8, 2011 9:09:22 PM by Hibernate Tools 3.4.0.CR1

/**
 * Pdev generated by hbm2java
 */
public class Pdev implements java.io.Serializable {

	private String objectId;
	private int arrayGroup;
	private String arrayGroupName;
	private int capacityInKb;
	private int chassis;
	private int pdevColumn;
	private int denseNumber;
	private int densePosition;
	private int depth;
	private int diskType;
	private String dkuType;
	private String model;
	private int pdevid;
	private int row;
	private int rpm;

	public Pdev() {
	}

	public Pdev(String objectId, int arrayGroup, String arrayGroupName,
			int capacityInKb, int chassis, int pdevColumn, int denseNumber,
			int densePosition, int depth, int diskType, String dkuType,
			String model, int pdevid, int row, int rpm) {
		this.objectId = objectId;
		this.arrayGroup = arrayGroup;
		this.arrayGroupName = arrayGroupName;
		this.capacityInKb = capacityInKb;
		this.chassis = chassis;
		this.pdevColumn = pdevColumn;
		this.denseNumber = denseNumber;
		this.densePosition = densePosition;
		this.depth = depth;
		this.diskType = diskType;
		this.dkuType = dkuType;
		this.model = model;
		this.pdevid = pdevid;
		this.row = row;
		this.rpm = rpm;
	}

	public String getObjectId() {
		return this.objectId;
	}

	public void setObjectId(String objectId) {
		this.objectId = objectId;
	}

	public int getArrayGroup() {
		return this.arrayGroup;
	}

	public void setArrayGroup(int arrayGroup) {
		this.arrayGroup = arrayGroup;
	}

	public String getArrayGroupName() {
		return this.arrayGroupName;
	}

	public void setArrayGroupName(String arrayGroupName) {
		this.arrayGroupName = arrayGroupName;
	}

	public int getCapacityInKb() {
		return this.capacityInKb;
	}

	public void setCapacityInKb(int capacityInKb) {
		this.capacityInKb = capacityInKb;
	}

	public int getChassis() {
		return this.chassis;
	}

	public void setChassis(int chassis) {
		this.chassis = chassis;
	}

	public int getPdevColumn() {
		return this.pdevColumn;
	}

	public void setPdevColumn(int pdevColumn) {
		this.pdevColumn = pdevColumn;
	}

	public int getDenseNumber() {
		return this.denseNumber;
	}

	public void setDenseNumber(int denseNumber) {
		this.denseNumber = denseNumber;
	}

	public int getDensePosition() {
		return this.densePosition;
	}

	public void setDensePosition(int densePosition) {
		this.densePosition = densePosition;
	}

	public int getDepth() {
		return this.depth;
	}

	public void setDepth(int depth) {
		this.depth = depth;
	}

	public int getDiskType() {
		return this.diskType;
	}

	public void setDiskType(int diskType) {
		this.diskType = diskType;
	}

	public String getDkuType() {
		return this.dkuType;
	}

	public void setDkuType(String dkuType) {
		this.dkuType = dkuType;
	}

	public String getModel() {
		return this.model;
	}

	public void setModel(String model) {
		this.model = model;
	}

	public int getPdevid() {
		return this.pdevid;
	}

	public void setPdevid(int pdevid) {
		this.pdevid = pdevid;
	}

	public int getRow() {
		return this.row;
	}

	public void setRow(int row) {
		this.row = row;
	}

	public int getRpm() {
		return this.rpm;
	}

	public void setRpm(int rpm) {
		this.rpm = rpm;
	}
	
	public void populate(ParseElement pElem){
		
		this.setArrayGroup(Integer.parseInt(pElem.getAttribute().get("arrayGroup")));
		this.setArrayGroupName(pElem.getAttribute().get("arrayGroupName"));
		this.setCapacityInKb(Integer.parseInt(pElem.getAttribute().get("capacityInKB")));
		this.setChassis(Integer.parseInt(pElem.getAttribute().get("chassis")));
		this.setDenseNumber(Integer.parseInt(pElem.getAttribute().get("denseNumber")));
		this.setDensePosition(Integer.parseInt(pElem.getAttribute().get("densePosition")));
		this.setDepth(Integer.parseInt(pElem.getAttribute().get("depth")));
		this.setDiskType(Integer.parseInt(pElem.getAttribute().get("diskType")));
		this.setDkuType(pElem.getAttribute().get("dkuType"));
		this.setModel(pElem.getAttribute().get("model"));
		this.setObjectId(pElem.getAttribute().get("objectID"));
		this.setPdevColumn(Integer.parseInt(pElem.getAttribute().get("pdevColumn")));
		this.setPdevid(Integer.parseInt(pElem.getAttribute().get("pdevid")));
		this.setRow(Integer.parseInt(pElem.getAttribute().get("row")));
		this.setRpm(Integer.parseInt(pElem.getAttribute().get("rpm")));
		
	}
}
