package com.hitachi.hibernate.entities;

import com.hitachi.objects.ParseElement;

// Generated Dec 1, 2011 1:15:41 AM by Hibernate Tools 3.4.0.CR1

/**
 * Pool generated by hbm2java
 */
public class Pool implements java.io.Serializable {

	private PoolId id;
	private int capacityInKb;
	private int capacityOfVvolsInKb;
	private int clprNumber;
	private String combination;
	private int controllerId;
	private int diskType;
	private int freeCapacityInKb;
	private int migrationInterval;
	private String monitorEndTime;
	private String monitorStartTime;
	private int numberOfPoolVols;
	private int numberOfVvols;
	private int overProvisioningLimit;
	private int overProvisioningPercent;
	private int overProvisioningWarning;
	private int poolFunction;
	private int poolType;
	private String raidLevel;
	private int rpm;
	private int status;
	private int threshold;
	private int threshold2;
	private int usageRate;
	private int volAlertNotice;

	public Pool() {
	}

	public Pool(PoolId id, int capacityInKb, int capacityOfVvolsInKb,
			int clprNumber, String combination, int controllerId, int diskType,
			int freeCapacityInKb, int migrationInterval, String monitorEndTime,
			String monitorStartTime, int numberOfPoolVols, int numberOfVvols,
			int overProvisioningLimit, int overProvisioningPercent,
			int overProvisioningWarning, int poolFunction, int poolType,
			String raidLevel, int rpm, int status, int threshold,
			int threshold2, int usageRate, int volAlertNotice) {
		this.id = id;
		this.capacityInKb = capacityInKb;
		this.capacityOfVvolsInKb = capacityOfVvolsInKb;
		this.clprNumber = clprNumber;
		this.combination = combination;
		this.controllerId = controllerId;
		this.diskType = diskType;
		this.freeCapacityInKb = freeCapacityInKb;
		this.migrationInterval = migrationInterval;
		this.monitorEndTime = monitorEndTime;
		this.monitorStartTime = monitorStartTime;
		this.numberOfPoolVols = numberOfPoolVols;
		this.numberOfVvols = numberOfVvols;
		this.overProvisioningLimit = overProvisioningLimit;
		this.overProvisioningPercent = overProvisioningPercent;
		this.overProvisioningWarning = overProvisioningWarning;
		this.poolFunction = poolFunction;
		this.poolType = poolType;
		this.raidLevel = raidLevel;
		this.rpm = rpm;
		this.status = status;
		this.threshold = threshold;
		this.threshold2 = threshold2;
		this.usageRate = usageRate;
		this.volAlertNotice = volAlertNotice;
	}

	public PoolId getId() {
		return this.id;
	}

	public void setId(PoolId id) {
		this.id = id;
	}

	public int getCapacityInKb() {
		return this.capacityInKb;
	}

	public void setCapacityInKb(int capacityInKb) {
		this.capacityInKb = capacityInKb;
	}

	public int getCapacityOfVvolsInKb() {
		return this.capacityOfVvolsInKb;
	}

	public void setCapacityOfVvolsInKb(int capacityOfVvolsInKb) {
		this.capacityOfVvolsInKb = capacityOfVvolsInKb;
	}

	public int getClprNumber() {
		return this.clprNumber;
	}

	public void setClprNumber(int clprNumber) {
		this.clprNumber = clprNumber;
	}

	public String getCombination() {
		return this.combination;
	}

	public void setCombination(String combination) {
		this.combination = combination;
	}

	public int getControllerId() {
		return this.controllerId;
	}

	public void setControllerId(int controllerId) {
		this.controllerId = controllerId;
	}

	public int getDiskType() {
		return this.diskType;
	}

	public void setDiskType(int diskType) {
		this.diskType = diskType;
	}

	public int getFreeCapacityInKb() {
		return this.freeCapacityInKb;
	}

	public void setFreeCapacityInKb(int freeCapacityInKb) {
		this.freeCapacityInKb = freeCapacityInKb;
	}

	public int getMigrationInterval() {
		return this.migrationInterval;
	}

	public void setMigrationInterval(int migrationInterval) {
		this.migrationInterval = migrationInterval;
	}

	public String getMonitorEndTime() {
		return this.monitorEndTime;
	}

	public void setMonitorEndTime(String monitorEndTime) {
		this.monitorEndTime = monitorEndTime;
	}

	public String getMonitorStartTime() {
		return this.monitorStartTime;
	}

	public void setMonitorStartTime(String monitorStartTime) {
		this.monitorStartTime = monitorStartTime;
	}

	public int getNumberOfPoolVols() {
		return this.numberOfPoolVols;
	}

	public void setNumberOfPoolVols(int numberOfPoolVols) {
		this.numberOfPoolVols = numberOfPoolVols;
	}

	public int getNumberOfVvols() {
		return this.numberOfVvols;
	}

	public void setNumberOfVvols(int numberOfVvols) {
		this.numberOfVvols = numberOfVvols;
	}

	public int getOverProvisioningLimit() {
		return this.overProvisioningLimit;
	}

	public void setOverProvisioningLimit(int overProvisioningLimit) {
		this.overProvisioningLimit = overProvisioningLimit;
	}

	public int getOverProvisioningPercent() {
		return this.overProvisioningPercent;
	}

	public void setOverProvisioningPercent(int overProvisioningPercent) {
		this.overProvisioningPercent = overProvisioningPercent;
	}

	public int getOverProvisioningWarning() {
		return this.overProvisioningWarning;
	}

	public void setOverProvisioningWarning(int overProvisioningWarning) {
		this.overProvisioningWarning = overProvisioningWarning;
	}

	public int getPoolFunction() {
		return this.poolFunction;
	}

	public void setPoolFunction(int poolFunction) {
		this.poolFunction = poolFunction;
	}

	public int getPoolType() {
		return this.poolType;
	}

	public void setPoolType(int poolType) {
		this.poolType = poolType;
	}

	public String getRaidLevel() {
		return this.raidLevel;
	}

	public void setRaidLevel(String raidLevel) {
		this.raidLevel = raidLevel;
	}

	public int getRpm() {
		return this.rpm;
	}

	public void setRpm(int rpm) {
		this.rpm = rpm;
	}

	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public int getThreshold() {
		return this.threshold;
	}

	public void setThreshold(int threshold) {
		this.threshold = threshold;
	}

	public int getThreshold2() {
		return this.threshold2;
	}

	public void setThreshold2(int threshold2) {
		this.threshold2 = threshold2;
	}

	public int getUsageRate() {
		return this.usageRate;
	}

	public void setUsageRate(int usageRate) {
		this.usageRate = usageRate;
	}

	public int getVolAlertNotice() {
		return this.volAlertNotice;
	}

	public void setVolAlertNotice(int volAlertNotice) {
		this.volAlertNotice = volAlertNotice;
	}
	
	public void populate(ParseElement pElem) {
		
		PoolId pid = new PoolId();
		pid.setObjectId(pElem.getAttribute().get("objectID"));
		pid.setPoolId(Integer.parseInt(pElem.getAttribute().get("poolID")));
		this.setId(pid);
		this.setCapacityInKb(Integer.parseInt(pElem.getAttribute().get("capacityInKB")));
		this.setCapacityOfVvolsInKb(Integer.parseInt(pElem.getAttribute().get("capacityOfVVolsInKB")));
		this.setClprNumber(Integer.parseInt(pElem.getAttribute().get("clprNumber")));
		this.setCombination(pElem.getAttribute().get("combination"));
		this.setControllerId(Integer.parseInt(pElem.getAttribute().get("controllerID")));
		this.setDiskType(Integer.parseInt(pElem.getAttribute().get("diskType")));
		this.setFreeCapacityInKb(Integer.parseInt(pElem.getAttribute().get("freeCapacityInKB")));
		this.setMigrationInterval(Integer.parseInt(pElem.getAttribute().get("migrationInterval")));
		this.setMonitorEndTime(pElem.getAttribute().get("monitorEndTime"));
		this.setMonitorStartTime(pElem.getAttribute().get("monitorStartTime"));
		this.setNumberOfPoolVols(Integer.parseInt(pElem.getAttribute().get("numberOfPoolVols")));
		this.setNumberOfVvols(Integer.parseInt(pElem.getAttribute().get("numberOfVVols")));
		this.setOverProvisioningLimit(Integer.parseInt(pElem.getAttribute().get("overProvisioningLimit")));
		this.setOverProvisioningPercent(Integer.parseInt(pElem.getAttribute().get("overProvisioningPercent")));
		this.setOverProvisioningWarning(Integer.parseInt(pElem.getAttribute().get("overProvisioningWarning")));
		this.setPoolFunction(Integer.parseInt(pElem.getAttribute().get("poolFunction")));
		this.setPoolType(Integer.parseInt(pElem.getAttribute().get("poolType")));
		this.setRaidLevel(pElem.getAttribute().get("raidLevel"));
		this.setRpm(Integer.parseInt(pElem.getAttribute().get("rpm")));
		this.setStatus(Integer.parseInt(pElem.getAttribute().get("status")));
		this.setThreshold(Integer.parseInt(pElem.getAttribute().get("threshold")));
		this.setThreshold2(Integer.parseInt(pElem.getAttribute().get("threshold2")));
		this.setUsageRate(Integer.parseInt(pElem.getAttribute().get("usageRate")));
		this.setVolAlertNotice(Integer.parseInt(pElem.getAttribute().get("volAlertNotice")));
	}
}
