package com.hitachi.hibernate.entities;

import com.hitachi.objects.ParseElement;

// Generated Dec 1, 2011 1:16:04 AM by Hibernate Tools 3.4.0.CR1

/**
 * Port generated by hbm2java
 */
public class Port implements java.io.Serializable {

	private PortId id;
	private int channelSpeed;
	private int controllerId;
	private String fibreAddress;
	private int keepAliveTime;
	private boolean lunSecurityEnabled;
	private int portNumber;
	private String portRole;
	private String portType;
	private int slprNumber;
	private String topology;
	private String worldWidePortName;

	public Port() {
	}

	public Port(PortId id, int channelSpeed, int controllerId,
			String fibreAddress, int keepAliveTime, boolean lunSecurityEnabled,
			int portNumber, String portRole, String portType, int slprNumber,
			String topology, String worldWidePortName) {
		this.id = id;
		this.channelSpeed = channelSpeed;
		this.controllerId = controllerId;
		this.fibreAddress = fibreAddress;
		this.keepAliveTime = keepAliveTime;
		this.lunSecurityEnabled = lunSecurityEnabled;
		this.portNumber = portNumber;
		this.portRole = portRole;
		this.portType = portType;
		this.slprNumber = slprNumber;
		this.topology = topology;
		this.worldWidePortName = worldWidePortName;
	}

	public PortId getId() {
		return this.id;
	}

	public void setId(PortId id) {
		this.id = id;
	}

	public int getChannelSpeed() {
		return this.channelSpeed;
	}

	public void setChannelSpeed(int channelSpeed) {
		this.channelSpeed = channelSpeed;
	}

	public int getControllerId() {
		return this.controllerId;
	}

	public void setControllerId(int controllerId) {
		this.controllerId = controllerId;
	}

	public String getFibreAddress() {
		return this.fibreAddress;
	}

	public void setFibreAddress(String fibreAddress) {
		this.fibreAddress = fibreAddress;
	}

	public int getKeepAliveTime() {
		return this.keepAliveTime;
	}

	public void setKeepAliveTime(int keepAliveTime) {
		this.keepAliveTime = keepAliveTime;
	}

	public boolean isLunSecurityEnabled() {
		return this.lunSecurityEnabled;
	}

	public void setLunSecurityEnabled(boolean lunSecurityEnabled) {
		this.lunSecurityEnabled = lunSecurityEnabled;
	}

	public int getPortNumber() {
		return this.portNumber;
	}

	public void setPortNumber(int portNumber) {
		this.portNumber = portNumber;
	}

	public String getPortRole() {
		return this.portRole;
	}

	public void setPortRole(String portRole) {
		this.portRole = portRole;
	}

	public String getPortType() {
		return this.portType;
	}

	public void setPortType(String portType) {
		this.portType = portType;
	}

	public int getSlprNumber() {
		return this.slprNumber;
	}

	public void setSlprNumber(int slprNumber) {
		this.slprNumber = slprNumber;
	}

	public String getTopology() {
		return this.topology;
	}

	public void setTopology(String topology) {
		this.topology = topology;
	}

	public String getWorldWidePortName() {
		return this.worldWidePortName;
	}

	public void setWorldWidePortName(String worldWidePortName) {
		this.worldWidePortName = worldWidePortName;
	}
	
	public void populate(ParseElement pElem){
		
		PortId pid = new PortId();
		pid.setObjectId(pElem.getAttribute().get("objectID"));
		pid.setDisplayName(pElem.getAttribute().get("displayName"));
		pid.setPortId(Integer.parseInt(pElem.getAttribute().get("portID")));
		this.setId(pid);
		this.setChannelSpeed(Integer.parseInt(pElem.getAttribute().get("channelSpeed")));
		this.setControllerId(Integer.parseInt(pElem.getAttribute().get("controllerID")));
		this.setFibreAddress(pElem.getAttribute().get("fibreAddress"));
		this.setKeepAliveTime(Integer.parseInt(pElem.getAttribute().get("keepAliveTime")));
		this.setLunSecurityEnabled(Boolean.parseBoolean(pElem.getAttribute().get("lunSecurityEnabled")));
		this.setPortNumber(Integer.parseInt(pElem.getAttribute().get("portNumber")));
		this.setPortRole(pElem.getAttribute().get("portRole"));
		this.setPortType(pElem.getAttribute().get("portType"));
		this.setSlprNumber(Integer.parseInt(pElem.getAttribute().get("slprNumber")));
		this.setTopology(pElem.getAttribute().get("topology"));
		this.setWorldWidePortName(pElem.getAttribute().get("worldWidePortName"));
	}
}
