package com.hitachi.hibernate.entities;

// Generated Dec 1, 2011 1:16:04 AM by Hibernate Tools 3.4.0.CR1

/**
 * PortId generated by hbm2java
 */
public class PortId implements java.io.Serializable {

	private int portId;
	private String displayName;
	private String objectId;

	public PortId() {
	}

	public PortId(int portId, String displayName, String objectId) {
		this.portId = portId;
		this.displayName = displayName;
		this.objectId = objectId;
	}

	public int getPortId() {
		return this.portId;
	}

	public void setPortId(int portId) {
		this.portId = portId;
	}

	public String getDisplayName() {
		return this.displayName;
	}

	public void setDisplayName(String displayName) {
		this.displayName = displayName;
	}

	public String getObjectId() {
		return this.objectId;
	}

	public void setObjectId(String objectId) {
		this.objectId = objectId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PortId))
			return false;
		PortId castOther = (PortId) other;

		return (this.getPortId() == castOther.getPortId())
				&& ((this.getDisplayName() == castOther.getDisplayName()) || (this
						.getDisplayName() != null
						&& castOther.getDisplayName() != null && this
						.getDisplayName().equals(castOther.getDisplayName())))
				&& ((this.getObjectId() == castOther.getObjectId()) || (this
						.getObjectId() != null
						&& castOther.getObjectId() != null && this
						.getObjectId().equals(castOther.getObjectId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getPortId();
		result = 37
				* result
				+ (getDisplayName() == null ? 0 : this.getDisplayName()
						.hashCode());
		result = 37 * result
				+ (getObjectId() == null ? 0 : this.getObjectId().hashCode());
		return result;
	}

}
