package com.hitachi.hibernate.entities;

import com.hitachi.objects.ParseElement;

// Generated Dec 1, 2011 1:16:26 AM by Hibernate Tools 3.4.0.CR1

/**
 * Portcontroller generated by hbm2java
 */
public class Portcontroller implements java.io.Serializable {

	private String objectId;
	private int card;
	private int cluster;
	private int controllerId;
	private String displayName;
	private int mode;
	private int type;

	public Portcontroller() {
	}

	public Portcontroller(String objectId, int card, int cluster,
			int controllerId, String displayName, int mode, int type) {
		this.objectId = objectId;
		this.card = card;
		this.cluster = cluster;
		this.controllerId = controllerId;
		this.displayName = displayName;
		this.mode = mode;
		this.type = type;
	}

	public String getObjectId() {
		return this.objectId;
	}

	public void setObjectId(String objectId) {
		this.objectId = objectId;
	}

	public int getCard() {
		return this.card;
	}

	public void setCard(int card) {
		this.card = card;
	}

	public int getCluster() {
		return this.cluster;
	}

	public void setCluster(int cluster) {
		this.cluster = cluster;
	}

	public int getControllerId() {
		return this.controllerId;
	}

	public void setControllerId(int controllerId) {
		this.controllerId = controllerId;
	}

	public String getDisplayName() {
		return this.displayName;
	}

	public void setDisplayName(String displayName) {
		this.displayName = displayName;
	}

	public int getMode() {
		return this.mode;
	}

	public void setMode(int mode) {
		this.mode = mode;
	}

	public int getType() {
		return this.type;
	}

	public void setType(int type) {
		this.type = type;
	}
	
	public void populate(ParseElement pElem){
		
		this.setCard(Integer.parseInt(pElem.getAttribute().get("card")));
		this.setCluster(Integer.parseInt(pElem.getAttribute().get("cluster")));
		this.setControllerId(Integer.parseInt(pElem.getAttribute().get("controllerID")));
		this.setMode(Integer.parseInt(pElem.getAttribute().get("mode")));
		this.setDisplayName(pElem.getAttribute().get("displayName"));
		this.setObjectId(pElem.getAttribute().get("objectID"));
		this.setType(Integer.parseInt(pElem.getAttribute().get("type")));
	}

}
