package com.hitachi.hibernate.entities;

import com.hitachi.objects.ParseElement;

// Generated Dec 1, 2011 1:18:08 AM by Hibernate Tools 3.4.0.CR1

/**
 * Wwn generated by hbm2java
 */
public class Wwn implements java.io.Serializable {

	private String wwn;
	private String nickname;
	private String wwn2hsd;

	public Wwn() {
	}

	public Wwn(String wwn, String nickname, String wwn2hsd) {
		this.wwn = wwn;
		this.nickname = nickname;
		this.wwn2hsd = wwn2hsd;
	}

	public String getWwn() {
		return this.wwn;
	}

	public void setWwn(String wwn) {
		this.wwn = wwn;
	}

	public String getNickname() {
		return this.nickname;
	}

	public void setNickname(String nickname) {
		this.nickname = nickname;
	}

	public String getWwn2hsd() {
		return this.wwn2hsd;
	}

	public void setWwn2hsd(String wwn2hsd) {
		this.wwn2hsd = wwn2hsd;
	}
	
	public void populate(ParseElement pElem,String hsdObj){
		
		this.setNickname(pElem.getAttribute().get("nickname"));
		this.setWwn(pElem.getAttribute().get("wwn"));
		this.setWwn2hsd(hsdObj);
	}

}
